const data = 
[
  {
    "_id": "63a46e0fc5b1e66b2ee92028",
    "popapp_id": 11880,
    "name": "Ensalada de brocoli",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "ensalada ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 40000.0,
    "discountedprice": 40000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11880/4300salad.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11880/640x640/4300salad.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11880/128x128/4300salad.jpg",
    "created_at": "2022-12-22T14:47:43.356+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      },
      {
        "id": 280,
        "name": "Adicionales",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11846,
            "name": "oregano",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11847,
            "name": "salsa Y",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11848,
            "name": "salsa x",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11849,
            "name": "mostaza",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11850,
            "name": "pimienta",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11851,
            "name": "sal",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "counters",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1764,
      "storeid": "",
      "name": "Ensaladas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92029",
    "popapp_id": 11862,
    "name": "crema uno",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno.",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 5000.0,
    "discountedprice": 5000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11862/5815sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11862/640x640/5815sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11862/128x128/5815sopa.jpg",
    "created_at": "2022-12-22T14:47:43.360+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9202a",
    "popapp_id": 11868,
    "name": "sandwich pavo",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "super sandwich, super sandwich, super sandwich, super sandwich, super sandwich, super sandwich, ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 20000.0,
    "discountedprice": 20000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11868/8151sand.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11868/640x640/8151sand.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11868/128x128/8151sand.jpg",
    "created_at": "2022-12-22T14:47:43.363+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1766,
      "storeid": "",
      "name": "Sándwiches",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9202b",
    "popapp_id": 11874,
    "name": "milo",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "ice ice ice ice ice ice ice ice ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 12000.0,
    "discountedprice": 12000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11874/7541ice.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11874/640x640/7541ice.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11874/128x128/7541ice.jpg",
    "created_at": "2022-12-22T14:47:43.367+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9202c",
    "popapp_id": 11871,
    "name": "Americano",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "americano cafe, americano cafe, americano cafe, americano cafe, americano cafe, ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 8000.0,
    "discountedprice": 8000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11871/42cff.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11871/640x640/42cff.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11871/128x128/42cff.jpg",
    "created_at": "2022-12-22T14:47:43.370+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1769,
      "storeid": "",
      "name": "Bebidas Calientes",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9202d",
    "popapp_id": 11877,
    "name": "torta de zanahoria",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "postreesss",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 40000.0,
    "discountedprice": 40000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11877/3861postre.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11877/640x640/3861postre.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11877/128x128/3861postre.jpg",
    "created_at": "2022-12-22T14:47:43.374+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1767,
      "storeid": "",
      "name": "Postres",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9202e",
    "popapp_id": 11872,
    "name": "latte",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "latte ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 10000.0,
    "discountedprice": 10000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2022-12-22T14:47:43.378+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1769,
      "storeid": "",
      "name": "Bebidas Calientes",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9202f",
    "popapp_id": 11878,
    "name": "torta de chocolate",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "postree",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 12000.0,
    "discountedprice": 12000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11878/9840postre.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11878/640x640/9840postre.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11878/128x128/9840postre.jpg",
    "created_at": "2022-12-22T14:47:43.381+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1767,
      "storeid": "",
      "name": "Postres",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92030",
    "popapp_id": 11881,
    "name": "Ensalada cesar",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "",
    "externalid": null,
    "isavailable": false,
    "isactive": false,
    "price": 50000.0,
    "discountedprice": 50000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11881/107salad.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11881/640x640/107salad.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11881/128x128/107salad.jpg",
    "created_at": "2022-12-22T14:47:43.384+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 280,
        "name": "Adicionales",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11846,
            "name": "oregano",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11847,
            "name": "salsa Y",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11848,
            "name": "salsa x",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11849,
            "name": "mostaza",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11850,
            "name": "pimienta",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11851,
            "name": "sal",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "counters",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1764,
      "storeid": "",
      "name": "Ensaladas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92031",
    "popapp_id": 11863,
    "name": "crema dos",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "crema deli",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 8000.0,
    "discountedprice": 8000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11863/3367sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11863/640x640/3367sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11863/128x128/3367sopa.jpg",
    "created_at": "2022-12-22T14:47:43.388+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92032",
    "popapp_id": 11869,
    "name": "sandwich res",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "res",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 25000.0,
    "discountedprice": 25000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2022-12-22T14:47:43.393+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1766,
      "storeid": "",
      "name": "Sándwiches",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92033",
    "popapp_id": 11875,
    "name": "limonada",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "ddddd",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 70000.0,
    "discountedprice": 70000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11875/2926ice.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11875/640x640/2926ice.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11875/128x128/2926ice.jpg",
    "created_at": "2022-12-22T14:47:43.402+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92034",
    "popapp_id": 11873,
    "name": "tinto",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "tinto col",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 5000.0,
    "discountedprice": 5000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11873/3126cff.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11873/640x640/3126cff.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11873/128x128/3126cff.jpg",
    "created_at": "2022-12-22T14:47:43.407+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1769,
      "storeid": "",
      "name": "Bebidas Calientes",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92035",
    "popapp_id": 11879,
    "name": "postre test con postre test nombre muy largo",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "postress",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 500000.0,
    "discountedprice": 500000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11879/168postre.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11879/640x640/168postre.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11879/128x128/168postre.jpg",
    "created_at": "2022-12-22T14:47:43.411+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1767,
      "storeid": "",
      "name": "Postres",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92036",
    "popapp_id": 11882,
    "name": "ensalada equis",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 71000.0,
    "discountedprice": 71000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11882/7820salad.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11882/640x640/7820salad.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11882/128x128/7820salad.jpg",
    "created_at": "2022-12-22T14:47:43.417+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 10,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1764,
      "storeid": "",
      "name": "Ensaladas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92037",
    "popapp_id": 11864,
    "name": "crema tres",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "crema deli",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 10000.0,
    "discountedprice": 10000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2022-12-22T14:47:43.421+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92038",
    "popapp_id": 11870,
    "name": "sandwich pollo",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "pollo pollo pollo pollo pollo ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 20000.0,
    "discountedprice": 20000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11870/3128sand.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11870/640x640/3128sand.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11870/128x128/3128sand.jpg",
    "created_at": "2022-12-22T14:47:43.425+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      },
      {
        "id": 282,
        "name": "Extras",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 1000.0,
            "minallowed": 0,
            "maxallowed": 3,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11860,
            "name": "Cebolla",
            "description": "",
            "price": 8000.0,
            "minallowed": 0,
            "maxallowed": 3,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11861,
            "name": "Piña",
            "description": "",
            "price": 3000.0,
            "minallowed": 0,
            "maxallowed": 3,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "counters",
        "maxallowed": 3,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1766,
      "storeid": "",
      "name": "Sándwiches",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee92039",
    "popapp_id": 11876,
    "name": "coca cola ",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "",
    "externalid": null,
    "isavailable": false,
    "isactive": false,
    "price": 8000.0,
    "discountedprice": 8000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11876/6517coca.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11876/640x640/6517coca.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11876/128x128/6517coca.jpg",
    "created_at": "2022-12-22T14:47:43.431+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9203a",
    "popapp_id": 11865,
    "name": "Sopa verde",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 12000.0,
    "discountedprice": 12000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11865/9498sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11865/640x640/9498sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11865/128x128/9498sopa.jpg",
    "created_at": "2022-12-22T14:47:43.435+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9203b",
    "popapp_id": 11937,
    "name": "agua super helada ok",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 50000.0,
    "discountedprice": 50000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2022-12-22T14:47:43.439+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9203c",
    "popapp_id": 11866,
    "name": "sopa azul",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "super sopa",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 15000.0,
    "discountedprice": 15000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11866/7732sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11866/640x640/7732sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11866/128x128/7732sopa.jpg",
    "created_at": "2022-12-22T14:47:43.442+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63a46e0fc5b1e66b2ee9203d",
    "popapp_id": 11867,
    "name": "sopa roja",
    "storeid": "0e5fca0b-ca18-424c-b155-65d6dd0dfbb0",
    "description": "super sopa x2",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 140000.0,
    "discountedprice": 140000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11867/9205sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11867/640x640/9205sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11867/128x128/9205sopa.jpg",
    "created_at": "2022-12-22T14:47:43.448+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 280,
        "name": "Adicionales",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11846,
            "name": "oregano",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11847,
            "name": "salsa Y",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11848,
            "name": "salsa x",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11849,
            "name": "mostaza",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11850,
            "name": "pimienta",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11851,
            "name": "sal",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      },
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 3,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41006",
    "popapp_id": 11939,
    "name": "combo 1",
    "storeid": "100",
    "description": "Descripción 1",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 2000.0,
    "discountedprice": 2000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu%2F11939%2F3642menu_20606_8382combo_2.jpeg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/popapptest-520dc.appspot.com/640x640/menu%2F11939%2F3642menu_20606_8382combo_2.jpeg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/popapptest-520dc.appspot.com/128x128/menu%2F11939%2F3642menu_20606_8382combo_2.jpeg",
    "created_at": "2023-02-01T13:59:09.029+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1778,
      "storeid": "",
      "name": "Recomendados del chef 1",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41007",
    "popapp_id": 11880,
    "name": "Ensalada de brocoli",
    "storeid": "100",
    "description": "ensalada ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 40000.0,
    "discountedprice": 40000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11880/4300salad.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11880/640x640/4300salad.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11880/128x128/4300salad.jpg",
    "created_at": "2023-02-01T13:59:09.036+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      },
      {
        "id": 280,
        "name": "Adicionales",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11846,
            "name": "oregano",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11847,
            "name": "salsa Y",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11848,
            "name": "salsa x",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11849,
            "name": "mostaza",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11850,
            "name": "pimienta",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11851,
            "name": "sal",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "counters",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1764,
      "storeid": "",
      "name": "Ensaladas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41008",
    "popapp_id": 11862,
    "name": "crema uno",
    "storeid": "100",
    "description": "crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno.",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 5000.0,
    "discountedprice": 5000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11862/5815sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11862/640x640/5815sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11862/128x128/5815sopa.jpg",
    "created_at": "2023-02-01T13:59:09.045+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41009",
    "popapp_id": 11940,
    "name": "Combo 2",
    "storeid": "100",
    "description": "Descripción 2",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 3000.0,
    "discountedprice": 3000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu%2F11940%2F8185menu_20606_8382combo_2.jpeg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/popapptest-520dc.appspot.com/640x640/menu%2F11940%2F8185menu_20606_8382combo_2.jpeg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/popapptest-520dc.appspot.com/128x128/menu%2F11940%2F8185menu_20606_8382combo_2.jpeg",
    "created_at": "2023-02-01T13:59:09.050+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1779,
      "storeid": "",
      "name": "Recomendados del chef 2",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4100a",
    "popapp_id": 11868,
    "name": "sandwich pavo",
    "storeid": "100",
    "description": "super sandwich, super sandwich, super sandwich, super sandwich, super sandwich, super sandwich, ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 20000.0,
    "discountedprice": 20000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11868/8151sand.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11868/640x640/8151sand.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11868/128x128/8151sand.jpg",
    "created_at": "2023-02-01T13:59:09.055+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1766,
      "storeid": "",
      "name": "Sándwiches",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4100b",
    "popapp_id": 11874,
    "name": "milo",
    "storeid": "100",
    "description": "ice ice ice ice ice ice ice ice ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 12000.0,
    "discountedprice": 12000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11874/7541ice.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11874/640x640/7541ice.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11874/128x128/7541ice.jpg",
    "created_at": "2023-02-01T13:59:09.061+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4100c",
    "popapp_id": 11871,
    "name": "Americano",
    "storeid": "100",
    "description": "americano cafe, americano cafe, americano cafe, americano cafe, americano cafe, ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 8000.0,
    "discountedprice": 8000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11871/42cff.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11871/640x640/42cff.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11871/128x128/42cff.jpg",
    "created_at": "2023-02-01T13:59:09.068+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1769,
      "storeid": "",
      "name": "Bebidas Calientes",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4100d",
    "popapp_id": 11877,
    "name": "torta de zanahoria",
    "storeid": "100",
    "description": "postreesss",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 40000.0,
    "discountedprice": 40000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11877/3861postre.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11877/640x640/3861postre.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11877/128x128/3861postre.jpg",
    "created_at": "2023-02-01T13:59:09.073+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1767,
      "storeid": "",
      "name": "Postres",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4100e",
    "popapp_id": 11872,
    "name": "latte",
    "storeid": "100",
    "description": "latte ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 10000.0,
    "discountedprice": 10000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2023-02-01T13:59:09.078+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1769,
      "storeid": "",
      "name": "Bebidas Calientes",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4100f",
    "popapp_id": 11878,
    "name": "torta de chocolate",
    "storeid": "100",
    "description": "postree",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 12000.0,
    "discountedprice": 12000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11878/9840postre.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11878/640x640/9840postre.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11878/128x128/9840postre.jpg",
    "created_at": "2023-02-01T13:59:09.082+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1767,
      "storeid": "",
      "name": "Postres",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41010",
    "popapp_id": 11881,
    "name": "Ensalada cesar",
    "storeid": "100",
    "description": "",
    "externalid": null,
    "isavailable": false,
    "isactive": false,
    "price": 50000.0,
    "discountedprice": 50000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11881/107salad.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11881/640x640/107salad.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11881/128x128/107salad.jpg",
    "created_at": "2023-02-01T13:59:09.090+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 280,
        "name": "Adicionales",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11846,
            "name": "oregano",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11847,
            "name": "salsa Y",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11848,
            "name": "salsa x",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11849,
            "name": "mostaza",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11850,
            "name": "pimienta",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11851,
            "name": "sal",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "counters",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1764,
      "storeid": "",
      "name": "Ensaladas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41011",
    "popapp_id": 11863,
    "name": "crema dos",
    "storeid": "100",
    "description": "crema deli",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 8000.0,
    "discountedprice": 8000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11863/3367sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11863/640x640/3367sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11863/128x128/3367sopa.jpg",
    "created_at": "2023-02-01T13:59:09.095+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41012",
    "popapp_id": 11869,
    "name": "sandwich res",
    "storeid": "100",
    "description": "res",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 25000.0,
    "discountedprice": 25000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2023-02-01T13:59:09.101+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1766,
      "storeid": "",
      "name": "Sándwiches",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41013",
    "popapp_id": 11875,
    "name": "limonada",
    "storeid": "100",
    "description": "ddddd",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 70000.0,
    "discountedprice": 70000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11875/2926ice.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11875/640x640/2926ice.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11875/128x128/2926ice.jpg",
    "created_at": "2023-02-01T13:59:09.105+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41014",
    "popapp_id": 11873,
    "name": "tinto",
    "storeid": "100",
    "description": "tinto col",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 5000.0,
    "discountedprice": 5000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11873/3126cff.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11873/640x640/3126cff.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11873/128x128/3126cff.jpg",
    "created_at": "2023-02-01T13:59:09.109+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1769,
      "storeid": "",
      "name": "Bebidas Calientes",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41015",
    "popapp_id": 11879,
    "name": "postre test con postre test nombre muy largo",
    "storeid": "100",
    "description": "postress",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 500000.0,
    "discountedprice": 500000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11879/168postre.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11879/640x640/168postre.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11879/128x128/168postre.jpg",
    "created_at": "2023-02-01T13:59:09.112+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1767,
      "storeid": "",
      "name": "Postres",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41016",
    "popapp_id": 11882,
    "name": "ensalada equis",
    "storeid": "100",
    "description": "",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 71000.0,
    "discountedprice": 71000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11882/7820salad.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11882/640x640/7820salad.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11882/128x128/7820salad.jpg",
    "created_at": "2023-02-01T13:59:09.117+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 10,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1764,
      "storeid": "",
      "name": "Ensaladas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41017",
    "popapp_id": 11864,
    "name": "crema tres",
    "storeid": "100",
    "description": "crema deli",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 10000.0,
    "discountedprice": 10000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2023-02-01T13:59:09.122+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41018",
    "popapp_id": 11870,
    "name": "sandwich pollo",
    "storeid": "100",
    "description": "pollo pollo pollo pollo pollo ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 20000.0,
    "discountedprice": 20000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11870/3128sand.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11870/640x640/3128sand.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11870/128x128/3128sand.jpg",
    "created_at": "2023-02-01T13:59:09.126+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      },
      {
        "id": 282,
        "name": "Extras",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 1000.0,
            "minallowed": 0,
            "maxallowed": 3,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11860,
            "name": "Cebolla",
            "description": "",
            "price": 8000.0,
            "minallowed": 0,
            "maxallowed": 3,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11861,
            "name": "Piña",
            "description": "",
            "price": 3000.0,
            "minallowed": 0,
            "maxallowed": 3,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "counters",
        "maxallowed": 3,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1766,
      "storeid": "",
      "name": "Sándwiches",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a41019",
    "popapp_id": 11876,
    "name": "coca cola ",
    "storeid": "100",
    "description": "",
    "externalid": null,
    "isavailable": false,
    "isactive": false,
    "price": 8000.0,
    "discountedprice": 8000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11876/6517coca.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11876/640x640/6517coca.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11876/128x128/6517coca.jpg",
    "created_at": "2023-02-01T13:59:09.130+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4101a",
    "popapp_id": 11865,
    "name": "Sopa verde",
    "storeid": "100",
    "description": "sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa sopa verde super sopa",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 12000.0,
    "discountedprice": 12000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11865/9498sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11865/640x640/9498sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11865/128x128/9498sopa.jpg",
    "created_at": "2023-02-01T13:59:09.136+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4101b",
    "popapp_id": 11938,
    "name": "producto de prueba 7720",
    "storeid": "100",
    "description": "",
    "externalid": "PRUEBA",
    "isavailable": true,
    "isactive": false,
    "price": 100000.0,
    "discountedprice": 100000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2023-02-01T13:59:09.140+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1767,
      "storeid": "",
      "name": "Postres",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4101c",
    "popapp_id": 11937,
    "name": "agua super helada ok",
    "storeid": "100",
    "description": "",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 50000.0,
    "discountedprice": 50000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://bacu.co/images/example.jpg",
    "detailimage": "https://bacu.co/images/example.jpg",
    "shortcutimage": "https://bacu.co/images/example.jpg",
    "created_at": "2023-02-01T13:59:09.143+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1768,
      "storeid": "",
      "name": "Bebidas Frias",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4101d",
    "popapp_id": 11866,
    "name": "sopa azul",
    "storeid": "100",
    "description": "super sopa",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 15000.0,
    "discountedprice": 15000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11866/7732sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11866/640x640/7732sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11866/128x128/7732sopa.jpg",
    "created_at": "2023-02-01T13:59:09.146+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63da702d6802b9e187a4101e",
    "popapp_id": 11867,
    "name": "sopa roja",
    "storeid": "100",
    "description": "super sopa x2",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 140000.0,
    "discountedprice": 140000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11867/9205sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11867/640x640/9205sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11867/128x128/9205sopa.jpg",
    "created_at": "2023-02-01T13:59:09.150+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 280,
        "name": "Adicionales",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11846,
            "name": "oregano",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11847,
            "name": "salsa Y",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11848,
            "name": "salsa x",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11849,
            "name": "mostaza",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11850,
            "name": "pimienta",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11851,
            "name": "sal",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      },
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "checkBoxes",
        "maxallowed": 3,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63ff6321ab3396be8036eaf0",
    "popapp_id": 11939,
    "name": "combo 1",
    "storeid": "101",
    "description": "Descripción 1",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 2000.0,
    "discountedprice": 2000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu%2F11939%2F3642menu_20606_8382combo_2.jpeg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/popapptest-520dc.appspot.com/640x640/menu%2F11939%2F3642menu_20606_8382combo_2.jpeg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/popapptest-520dc.appspot.com/128x128/menu%2F11939%2F3642menu_20606_8382combo_2.jpeg",
    "created_at": "2023-03-01T14:37:21.051+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1778,
      "storeid": "",
      "name": "Recomendados del chef 1",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63ff6321ab3396be8036eaf1",
    "popapp_id": 11862,
    "name": "crema uno",
    "storeid": "101",
    "description": "crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno, crema uno.",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 5000.0,
    "discountedprice": 5000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11862/5815sopa.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11862/640x640/5815sopa.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11862/128x128/5815sopa.jpg",
    "created_at": "2023-03-01T14:37:21.055+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [],
    "category": {
      "id": 1763,
      "storeid": "",
      "name": "Sopas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  },
  {
    "_id": "63ff6321ab3396be8036eaf2",
    "popapp_id": 11880,
    "name": "Ensalada de brocoli",
    "storeid": "101",
    "description": "ensalada ",
    "externalid": null,
    "isavailable": true,
    "isactive": false,
    "price": 40000.0,
    "discountedprice": 40000.0,
    "minallowed": 0,
    "maxallowed": 0,
    "index": 0,
    "imageurl": "https://storage.googleapis.com/popapptest-520dc.appspot.com/menu/11880/4300salad.jpg",
    "detailimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11880/640x640/4300salad.jpg",
    "shortcutimage": "https://d3hkr469bej70u.cloudfront.net/images/menu/11880/128x128/4300salad.jpg",
    "created_at": "2023-03-01T14:37:21.059+0000",
    "valid_until": "0001-01-01T00:00:00.000+0000",
    "tags": [],
    "discounts": [],
    "modifiergroups": [
      {
        "id": 281,
        "name": "Acompañamientos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11854,
            "name": "Pepinillos",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11855,
            "name": "Aceitunas",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11856,
            "name": "Queso",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11857,
            "name": "Aguacate",
            "description": "",
            "price": 2000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11858,
            "name": "Berenjena",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11859,
            "name": "Arroz",
            "description": "",
            "price": 5000.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      },
      {
        "id": 280,
        "name": "Adicionales",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11846,
            "name": "oregano",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11847,
            "name": "salsa Y",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11848,
            "name": "salsa x",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11849,
            "name": "mostaza",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11850,
            "name": "pimienta",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11851,
            "name": "sal",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 10,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "counters",
        "maxallowed": 10,
        "minallowed": 0
      },
      {
        "id": 279,
        "name": "con cubiertos",
        "isavailable": true,
        "modifiers": [
          {
            "id": 11852,
            "name": "no",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          },
          {
            "id": 11853,
            "name": "si",
            "description": "",
            "price": 0.0,
            "minallowed": 0,
            "maxallowed": 1,
            "index": 0,
            "imageurl": null,
            "isavailable": true
          }
        ],
        "selecttype": "radioBtn",
        "maxallowed": 1,
        "minallowed": 0
      }
    ],
    "category": {
      "id": 1764,
      "storeid": "",
      "name": "Ensaladas",
      "categorytype": "",
      "icon": "",
      "canschedule": false,
      "show": false,
      "index": 0
    }
  }
]; 